/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + available external tools */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default settings and upload limits (drives the UI form) */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an image and start a conversion job */
        post: operations["convert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new job from the same upload with new settings (palette edit/merge) */
        post: operations["rerunJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        /** Poll job status/result */
        get: operations["getJob"];
        put?: never;
        post?: never;
        /** Delete a job and its files */
        delete: operations["deleteJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/files/{kind}": {
        parameters: {
            query?: {
                /** @description Send Content-Disposition: attachment */
                download?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
                kind: "original" | "svg" | "ai" | "eps" | "png";
            };
            cookie?: never;
        };
        /** Download an input/output file */
        get: operations["getJobFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigResponse */
        ConfigResponse: {
            defaults: components["schemas"]["Settings"];
            limits: components["schemas"]["Limits"];
        };
        /**
         * DetailLevel
         * @enum {string}
         */
        DetailLevel: "low" | "medium" | "high";
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description Machine-readable, e.g. invalid_image, stage_failed, too_large.
             */
            code: string;
            /** Message */
            message: string;
            /** @default null */
            stage: components["schemas"]["PipelineStage"] | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * FileKind
         * @enum {string}
         */
        FileKind: "original" | "svg" | "ai" | "eps" | "png";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
            /**
             * Schema Version
             * @default 1.0.0
             */
            schema_version: string;
            /**
             * Capabilities
             * @description e.g. {'inkscape': true, 'vtracer': true, 'potrace': false}
             */
            capabilities: {
                [key: string]: boolean;
            };
        };
        /** ImageClass */
        ImageClass: {
            label: components["schemas"]["ImageClassLabel"];
            /** Confidence */
            confidence: number;
            /**
             * Forced
             * @description True when Settings.mode overrode auto-detection.
             * @default false
             */
            forced: boolean;
            /**
             * Features
             * @description Diagnostic features used to decide.
             */
            features?: {
                [key: string]: number;
            };
        };
        /**
         * ImageClassLabel
         * @enum {string}
         */
        ImageClassLabel: "line_art" | "flat_color" | "mixed";
        /** JobFile */
        JobFile: {
            kind: components["schemas"]["FileKind"];
            /**
             * Url
             * @description Relative URL, e.g. /api/v1/jobs/{id}/files/svg
             */
            url: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** JobResponse */
        JobResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            stage: components["schemas"]["PipelineStage"];
            /** Progress */
            progress: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Expires At
             * Format: date-time
             * @description When the job and its files will be deleted.
             */
            expires_at: string;
            /** Filename */
            filename: string;
            settings: components["schemas"]["Settings"];
            /**
             * Source Job Id
             * @description Set when this job is a re-run of another job.
             * @default null
             */
            source_job_id: string | null;
            /** @default null */
            result: components["schemas"]["JobResult"] | null;
            /** @default null */
            error: components["schemas"]["ErrorDetail"] | null;
        };
        /** JobResult */
        JobResult: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            image_class: components["schemas"]["ImageClass"];
            /** Layer Count */
            layer_count: number;
            /** Palette Hex */
            palette_hex: string[];
            quality: components["schemas"]["QualityReport"];
            /** Files */
            files: components["schemas"]["JobFile"][];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** Limits */
        Limits: {
            /**
             * Max Upload Bytes
             * @default 20971520
             */
            max_upload_bytes: number;
            /**
             * Job Ttl Seconds
             * @default 3600
             */
            job_ttl_seconds: number;
            /**
             * Max Pixels
             * @default 36000000
             */
            max_pixels: number;
            /** Accepted Media Types */
            accepted_media_types?: string[];
        };
        /**
         * LineMode
         * @enum {string}
         */
        LineMode: "outline" | "centerline";
        /** MetricCheck */
        MetricCheck: {
            name: components["schemas"]["MetricName"];
            /** Value */
            value: number;
            /** Threshold */
            threshold: number;
            /**
             * Comparator
             * @enum {string}
             */
            comparator: "<" | "<=" | ">=" | ">";
            /** Passed */
            passed: boolean;
        };
        /**
         * MetricName
         * @enum {string}
         */
        MetricName: "ssim" | "max_delta_e" | "mean_delta_e" | "gap_ratio" | "alpha_iou" | "processing_time_s" | "svg_valid";
        /**
         * OutputFormat
         * @enum {string}
         */
        OutputFormat: "svg" | "ai" | "eps" | "png";
        /**
         * PipelineStage
         * @enum {string}
         */
        PipelineStage: "upload" | "preprocess" | "classify" | "quantize" | "extract_lines" | "vectorize" | "assemble" | "export" | "evaluate" | "done";
        /**
         * ProcessingMode
         * @enum {string}
         */
        ProcessingMode: "auto" | "line_art" | "flat_color" | "mixed";
        /**
         * QualityReport
         * @description Metric definitions:
         *
         *     * ssim: SSIM on grayscale after alpha-compositing source and preview over white,
         *       computed at source resolution.
         *     * mean/max_delta_e: CIEDE2000 between each fill layer's color_hex and the dominant
         *       (median in LAB) color of its palette region, where the region's pixels are taken from the
         *       ORIGINAL source image resampled nearest-neighbour onto the processing grid (not pre.image,
         *       so preprocessing color shifts are caught). Line layers compare against LineMap-covered
         *       pixels when a LineMap exists, restricted to their own palette region when palette_index
         *       is set (a LineMap may hold strokes of several colors). A palette region holding >= 0.5% of opaque pixels that no
         *       layer represents is scored with the color preview.png renders there. Background layers count.
         *     * gap_ratio: render preview.png over transparency; among source pixels with alpha >= 128
         *       after a 1-px erosion (so silhouette anti-aliasing is ignored), the fraction whose preview
         *       alpha < 128. Detects hairline gaps between color regions.
         *     * alpha_iou: IoU of (source alpha >= 128) vs (preview alpha >= 128); None if opaque.
         *     * node_count: total M/L/C segment endpoints over all VectorDocument layers (Z not counted).
         *     * file_size_bytes: size of the optimized output.svg.
         */
        QualityReport: {
            /** Ssim */
            ssim: number;
            /** Mean Delta E */
            mean_delta_e: number;
            /** Max Delta E */
            max_delta_e: number;
            /** Gap Ratio */
            gap_ratio: number;
            /**
             * Alpha Iou
             * @default null
             */
            alpha_iou: number | null;
            /** Node Count */
            node_count: number;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Processing Time S */
            processing_time_s: number;
            /** Checks */
            checks: components["schemas"]["MetricCheck"][];
            /** Passed */
            readonly passed: boolean;
        };
        /**
         * RerunRequest
         * @description Re-run a finished job's upload with new settings (e.g. an edited palette_override).
         */
        RerunRequest: {
            settings: components["schemas"]["Settings"];
        };
        /**
         * Settings
         * @description User-controllable conversion settings (API body + UI form).
         */
        Settings: {
            /** @default auto */
            mode: components["schemas"]["ProcessingMode"];
            /**
             * Max Colors
             * @description None = auto-detect.
             * @default null
             */
            max_colors: number | null;
            /** @default medium */
            detail_level: components["schemas"]["DetailLevel"];
            /** @default outline */
            line_mode: components["schemas"]["LineMode"];
            /**
             * Smoothing
             * @description 0 = polygonal, 100 = maximally smooth curves.
             * @default 50
             */
            smoothing: number;
            /**
             * Remove Background
             * @description Preprocess makes the detected background transparent (PreprocessResult.background_removed).
             * @default false
             */
            remove_background: boolean;
            /**
             * Palette Override
             * @description User-edited palette for a re-run (UI edit/merge). When set, quantize assigns every opaque pixel to the nearest of these colors in LAB and skips auto-detection; max_colors is ignored.
             * @default null
             */
            palette_override: string[] | null;
            /** Output Formats */
            output_formats?: components["schemas"]["OutputFormat"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    convert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PNG or JPEG, <= 20971520 bytes
                     */
                    file: string;
                    /** @description JSON-encoded Settings; omitted fields use defaults */
                    settings?: string;
                };
            };
        };
        responses: {
            /** @description Job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid settings or undecodable image */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rerunJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerunRequest"];
            };
        };
        responses: {
            /** @description New job accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Unknown or expired job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid settings */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Unknown job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getJobFile: {
        parameters: {
            query?: {
                /** @description Send Content-Disposition: attachment */
                download?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
                kind: "original" | "svg" | "ai" | "eps" | "png";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                    "image/png": string;
                    "image/jpeg": string;
                    "application/postscript": string;
                    "application/illustrator": string;
                };
            };
            /** @description Unknown job, or file not produced / not ready */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
